### ISSUE TITLE
Mehrere Aktivitäten anlegen für eine Stadt // Unterkapitel anlegen wie in den Entwürfen - siehe Slide 12 

### ISSUE THREAD

**Issue by A4536** [seebruecke-org/moving-cities-frontend#57]

**Comment by A4536** [comment]
Es gibt ein Kapitel 4 und es gibt Unterkapitel von Kapitel 4, diese sind jeweils eine Aktivität

**Comment by A4536** [comment]
Ich kann mehrere Aktivitäten zuordnen aber diese werden nicht angezeigt

**Comment by gustavpursche** [comment]
Das funktioniert nach einem CMS Update nun endlich. Ich habe es mal beispielhaft fuer Tilburg eingepflegt: https://moving-cities.vercel.app/cities/netherlands/tilburg
