### ISSUE TITLE
Wenn ich auf dem Länderprofil gelandet bin, muss ich mit einem Klick zurück zum Sadtprofil kommen, auf dem ich war

### ISSUE THREAD

**Issue by A4536** [seebruecke-org/moving-cities-frontend#67]

**Comment by A4536** [comment]
Wäre schön jetzt zu haben, aber kommt auf den Aufwand an. Wenn zu aufwändig, würde ich es auf die Weiterentwicklung verschieben

**Comment by gustavpursche** [comment]
Das ist tatsaechlich aufwendiger, als ich es gedacht haette. Ich wuerde das hier mal schliessen, weil die eigentlich dafuer gedachte Browser Funktion "zurueck" an der Stelle auch gut funktioniert.
