### ISSUE TITLE
Vorschau-Fenster für Stadtprofil wieder schließbar machen, durch Button auf Vorschaufenster

### ISSUE THREAD

**Issue by A4536** [seebruecke-org/moving-cities-frontend#71]

**Comment by A4536** [comment]
Der Butto hinter Städtenamen auf der rechten Seite ist gut, aber man findet ihn nicht so schnell

**Comment by A4536** [comment]
Wäre schön jetzt zu haben, aber kommt auf den Aufwand an. Wenn zu aufwändig, würde ich es auf die Weiterentwicklung verschieben

**Comment by gustavpursche** [comment]
Das ist nun drinnen.
