### ISSUE TITLE
Filterfunktion bei Aktivitis funktioniert noch nicht

### ISSUE THREAD

**Issue by A4536** [seebruecke-org/moving-cities-frontend#73]
Wäre schön jetzt zu haben, aber kommt auf den Aufwand an. Wenn zu aufwändig, würde ich es auf die Weiterentwicklung verschieben

**Comment by gustavpursche** [comment]
Die sollten nun wieder funktionieren. Da hatte sich nur nen kleiner Fehler eingeschlichen.
